### ISSUE TITLE
Pip upgrade failing

### ISSUE THREAD

**Issue by lil-cain** [rackspace-cookbooks/stack_commons#104]
Hey,

https://github.com/rackspace-cookbooks/stack_commons/blob/master/recipes/python.rb is failing, as the version of pip that python::pip updates pip too breaks easy_install. I've worked around this by setting 
`node.force_override['python']['setuptools_version'] = '0.6.rc10'`
(This is the version that comes with RHEL.)

**Comment by martinb3** [comment]
Hi @lil-cain -- we've worked on this some before, and thought it was resolved (the test suites are currently doing this and passing). Could you let us know what distro and version is failing, and what version of stack_commons is failing, and how you're calling it (or a runlist)?

Also, are you *sure* that `stack_commons::python` is running before any other recipes that need python? In the past, this has been due to some other cookbook calling python stuff before `stack_commons::python` is called to perform the workaround.

**Comment by prometheanfire** [comment]
ping for more info :D
